server:
  port: 8085
spring:
  application:
    name: qds-cloud-consumer-feign-hystrix

# eureka ≈‰÷√
eureka:
  client:
    serviceUrl:
      defaultZone: http://xieyimin:123456@localhost:8761/eureka
logging:
  level:
    root: INFO

