server:
  port: 8085
spring:
  application:
    name: qds-cloud-consumer-feign-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://xieyimin:123456@localhost:8761/eureka

logging:
  level:
    root: INFO

ribbon:
  ConnectTimeout: 1000 # 连接超时时长
  ReadTimeout: 2000 # 数据通信超时时长
  MaxAutoRetries: 0 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 0 # 重试多少次服务
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试

#支持对请求和响应进行GZIP压缩，以减少通信过程中的性能损耗
feign:
  compression:
    request:
      enabled: true # 开启请求压缩
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048 # 设置触发压缩的大小下限
    response:
      enabled: true # 开启响应压缩



