server:
  port: 7901
spring:
  application:
    name: provider-user


eureka:
  client:
    serviceUrl:
      defaultZone: http://xieyimin:123456@localhost:8761/eureka

logging:
  level:
    root: INFO
