server:
  port: 8083
spring:
  application:
    name: qds-cloud-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://xieyimin:123456@localhost:8761/eureka
logging:
  level:
    root: INFO
